/**
 * MillionsNest Connect - Realistic Local Demo Dataset
 * Strictly tagged as DEMO_MODE - No production secrets or live APIs.
 */

import {
  EffectiveEcosystemContext,
  Contact,
  Conversation,
  UnifiedMessage,
  AgentDefinition,
  KnowledgeSource,
  AutomationDefinition,
  ToolDefinition,
  AuditEvent,
  ChannelConnection,
  AppManifest,
} from '../types';

export const mockEcosystemContext: EffectiveEcosystemContext = {
  mode: 'DEMO_MODE',
  user: {
    id: 'usr_daniel_01',
    name: 'Pr. Daniel Cunha',
    email: 'pastordanielpcunha@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    globalRole: 'ecosystem_admin',
    globalCapabilities: ['livingLibrary.manage', 'analytics.view_global', 'audit.view_all'],
  },
  activeOrganization: {
    id: 'org_londrina_01',
    name: 'Igreja Central Londrina',
    slug: 'igreja-central-londrina',
    plan: 'enterprise',
    isCanonical: true,
  },
  availableOrganizations: [
    {
      id: 'org_londrina_01',
      name: 'Igreja Central Londrina',
      slug: 'igreja-central-londrina',
      plan: 'enterprise',
      isCanonical: true,
    },
    {
      id: 'org_curitiba_02',
      name: 'Comunidade Graça Curitiba',
      slug: 'comunidade-graca-curitiba',
      plan: 'pro',
      isCanonical: true,
    },
    {
      id: 'org_maringa_03',
      name: 'Igreja Esperança Maringá',
      slug: 'igreja-esperanca-maringa',
      plan: 'starter',
      isCanonical: true,
    },
  ],
  memberships: [
    {
      id: 'mem_01',
      userId: 'usr_daniel_01',
      organizationId: 'org_londrina_01',
      organizationName: 'Igreja Central Londrina',
      role: 'owner',
      permissions: ['musicscale.schedules.manage', 'musicscale.repertoire.manage', 'connect.agent.admin'],
    },
    {
      id: 'mem_02',
      userId: 'usr_daniel_01',
      organizationId: 'org_curitiba_02',
      organizationName: 'Comunidade Graça Curitiba',
      role: 'admin',
      permissions: ['musicscale.schedules.view', 'connect.agent.view'],
    },
  ],
  effectiveCapabilities: ['livingLibrary.manage', 'analytics.view_global', 'audit.view_all'],
};

export const mockContacts: Contact[] = [
  {
    id: 'cnt_01',
    name: 'Gabriel Santos',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    email: 'gabriel.santos@email.com',
    phone: '+55 43 99812-4455',
    instagramHandle: '@gabrielsantos_music',
    identities: [
      {
        channel: 'whatsapp',
        channelUserId: '+5543998124455',
        linkedUserId: 'usr_mn_8812',
        isVerified: true,
        linkedAt: '2026-03-15T10:20:00Z',
      },
      {
        channel: 'instagram',
        channelUserId: '178414012345678',
        linkedUserId: 'usr_mn_8812',
        isVerified: true,
        linkedAt: '2026-03-15T10:22:00Z',
      },
    ],
    linkingStatus: 'vinculado',
    consents: {
      marketing: true,
      support: true,
      dataRetention: true,
      updatedAt: '2026-03-15T10:20:00Z',
    },
    preferredLanguage: 'pt-BR',
    authorizedOrgsHistory: [
      { organizationId: 'org_londrina_01', organizationName: 'Igreja Central Londrina', grantedAt: '2026-03-15T10:20:00Z' },
    ],
    tags: ['Músico', 'Teclado', 'Escala Ativa', 'VIP'],
    createdAt: '2026-03-15T10:20:00Z',
  },
  {
    id: 'cnt_02',
    name: 'Mariana Costa',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    email: 'mariana.costa@gmail.com',
    phone: '+55 43 98877-1122',
    instagramHandle: '@marianacosta_vocal',
    identities: [
      {
        channel: 'whatsapp',
        channelUserId: '+5543988771122',
        isVerified: false,
      },
    ],
    linkingStatus: 'pendente',
    consents: {
      marketing: false,
      support: true,
      dataRetention: true,
      updatedAt: '2026-06-01T14:10:00Z',
    },
    preferredLanguage: 'pt-BR',
    authorizedOrgsHistory: [],
    tags: ['Vocalista', 'Visitante'],
    createdAt: '2026-06-01T14:10:00Z',
  },
  {
    id: 'cnt_03',
    name: 'Carlos Eduardo',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    instagramHandle: '@carlosedu_bassist',
    identities: [
      {
        channel: 'instagram',
        channelUserId: '178414099887766',
        isVerified: false,
      },
    ],
    linkingStatus: 'nao_vinculado',
    consents: {
      marketing: false,
      support: true,
      dataRetention: false,
      updatedAt: '2026-07-20T11:00:00Z',
    },
    preferredLanguage: 'pt-BR',
    authorizedOrgsHistory: [],
    tags: ['Instagram Lead', 'Baixista'],
    createdAt: '2026-07-20T11:00:00Z',
  },
];

export const mockTools: ToolDefinition[] = [
  {
    id: 'tool_musicscale_list_schedules',
    appId: 'musicscale',
    name: 'listSchedules',
    version: '1.2.0',
    title: 'Listar Escalas do MusicScale',
    description: 'Recupera as próximas escalas e escalas anteriores com status de confirmação dos músicos.',
    inputSchema: JSON.stringify({ organizationId: 'string', limit: 'number', status: 'string' }),
    outputSchema: JSON.stringify({ schedules: 'array' }),
    requiredPermissions: ['musicscale.schedules.view'],
    organizationScoped: true,
    riskLevel: 'R1_AUTH_READ',
    confirmationPolicy: 'automatic',
    readOnly: true,
    idempotencyPolicy: 'cacheable_60s',
    supportsPreview: true,
    supportsUndo: false,
    timeoutMs: 3000,
    auditEventType: 'TOOL_MUSICSCALE_LIST_SCHEDULES',
  },
  {
    id: 'tool_musicscale_get_schedule',
    appId: 'musicscale',
    name: 'getSchedule',
    version: '1.2.0',
    title: 'Ver Detalhes da Escala',
    description: 'Obtém detalhes completos de uma escala incluindo repertório, músicos e horários de ensaio.',
    inputSchema: JSON.stringify({ scheduleId: 'string' }),
    outputSchema: JSON.stringify({ schedule: 'object' }),
    requiredPermissions: ['musicscale.schedules.view'],
    organizationScoped: true,
    riskLevel: 'R1_AUTH_READ',
    confirmationPolicy: 'automatic',
    readOnly: true,
    idempotencyPolicy: 'cacheable_300s',
    supportsPreview: true,
    supportsUndo: false,
    timeoutMs: 3000,
    auditEventType: 'TOOL_MUSICSCALE_GET_SCHEDULE',
  },
  {
    id: 'tool_musicscale_create_schedule_draft',
    appId: 'musicscale',
    name: 'createScheduleDraft',
    version: '1.2.0',
    title: 'Criar Rascunho de Escala',
    description: 'Cria um rascunho de escala para confirmação posterior da equipe de louvor.',
    inputSchema: JSON.stringify({ title: 'string', date: 'string', serviceTime: 'string' }),
    outputSchema: JSON.stringify({ draftId: 'string', status: 'string' }),
    requiredPermissions: ['musicscale.schedules.manage'],
    organizationScoped: true,
    riskLevel: 'R2_REVERSIBLE_WRITE',
    confirmationPolicy: 'user_confirmation',
    readOnly: false,
    idempotencyPolicy: 'unique_request_id',
    supportsPreview: true,
    supportsUndo: true,
    timeoutMs: 5000,
    auditEventType: 'TOOL_MUSICSCALE_CREATE_DRAFT',
  },
  {
    id: 'tool_musicscale_clone_schedule',
    appId: 'musicscale',
    name: 'cloneSchedule',
    version: '1.2.0',
    title: 'Clonar Escala',
    description: 'Duplica uma estrutura de escala existente para uma nova data com os mesmos voluntários.',
    inputSchema: JSON.stringify({ sourceScheduleId: 'string', targetDate: 'string' }),
    outputSchema: JSON.stringify({ newScheduleId: 'string' }),
    requiredPermissions: ['musicscale.schedules.manage'],
    organizationScoped: true,
    riskLevel: 'R2_REVERSIBLE_WRITE',
    confirmationPolicy: 'user_confirmation',
    readOnly: false,
    idempotencyPolicy: 'unique_request_id',
    supportsPreview: true,
    supportsUndo: true,
    timeoutMs: 5000,
    auditEventType: 'TOOL_MUSICSCALE_CLONE_SCHEDULE',
  },
  {
    id: 'tool_musicscale_list_members',
    appId: 'musicscale',
    name: 'listMembers',
    version: '1.1.0',
    title: 'Listar Integrantes do Louvor',
    description: 'Lista voluntários, vozes, instrumentos e disponibilidade cadastrada no MusicScale.',
    inputSchema: JSON.stringify({ organizationId: 'string' }),
    outputSchema: JSON.stringify({ members: 'array' }),
    requiredPermissions: ['musicscale.members.view'],
    organizationScoped: true,
    riskLevel: 'R1_AUTH_READ',
    confirmationPolicy: 'automatic',
    readOnly: true,
    idempotencyPolicy: 'cacheable_300s',
    supportsPreview: true,
    supportsUndo: false,
    timeoutMs: 3000,
    auditEventType: 'TOOL_MUSICSCALE_LIST_MEMBERS',
  },
  {
    id: 'tool_musicscale_add_member',
    appId: 'musicscale',
    name: 'addMember',
    version: '1.1.0',
    title: 'Adicionar Membro à Equipe',
    description: 'Insere um novo músico ou vocalista com papéis definidos na equipe de louvor da organização.',
    inputSchema: JSON.stringify({ name: 'string', role: 'string', phone: 'string' }),
    outputSchema: JSON.stringify({ memberId: 'string' }),
    requiredPermissions: ['musicscale.members.manage'],
    organizationScoped: true,
    riskLevel: 'R2_REVERSIBLE_WRITE',
    confirmationPolicy: 'user_confirmation',
    readOnly: false,
    idempotencyPolicy: 'unique_request_id',
    supportsPreview: true,
    supportsUndo: true,
    timeoutMs: 4000,
    auditEventType: 'TOOL_MUSICSCALE_ADD_MEMBER',
  },
  {
    id: 'tool_musicscale_list_repertoire',
    appId: 'musicscale',
    name: 'listRepertoire',
    version: '1.3.0',
    title: 'Listar Repertório Local',
    description: 'Pesquisa músicas cadastradas no repertório da igreja local.',
    inputSchema: JSON.stringify({ query: 'string', tag: 'string' }),
    outputSchema: JSON.stringify({ songs: 'array' }),
    requiredPermissions: ['musicscale.repertoire.view'],
    organizationScoped: true,
    riskLevel: 'R1_AUTH_READ',
    confirmationPolicy: 'automatic',
    readOnly: true,
    idempotencyPolicy: 'cacheable_120s',
    supportsPreview: true,
    supportsUndo: false,
    timeoutMs: 3000,
    auditEventType: 'TOOL_MUSICSCALE_LIST_REPERTOIRE',
  },
  {
    id: 'tool_musicscale_add_song_to_repertoire',
    appId: 'musicscale',
    name: 'addSongToRepertoire',
    version: '1.3.0',
    title: 'Adicionar Música ao Repertório Local',
    description: 'Cadastra uma nova música no catálogo da organização local com tom e cifra.',
    inputSchema: JSON.stringify({ title: 'string', artist: 'string', key: 'string' }),
    outputSchema: JSON.stringify({ songId: 'string' }),
    requiredPermissions: ['musicscale.repertoire.manage'],
    organizationScoped: true,
    riskLevel: 'R2_REVERSIBLE_WRITE',
    confirmationPolicy: 'user_confirmation',
    readOnly: false,
    idempotencyPolicy: 'unique_request_id',
    supportsPreview: true,
    supportsUndo: true,
    timeoutMs: 4000,
    auditEventType: 'TOOL_MUSICSCALE_ADD_REPERTOIRE',
  },
  {
    id: 'tool_musicscale_search_living_library',
    appId: 'musicscale',
    name: 'searchLivingLibrary',
    version: '2.0.0',
    title: 'Pesquisar Biblioteca Viva Global',
    description: 'Busca acordos, arranjos e letras homologadas na Biblioteca Viva compartilhada entre igrejas.',
    inputSchema: JSON.stringify({ query: 'string' }),
    outputSchema: JSON.stringify({ results: 'array' }),
    requiredPermissions: [],
    organizationScoped: false,
    riskLevel: 'R0_PUBLIC',
    confirmationPolicy: 'automatic',
    readOnly: true,
    idempotencyPolicy: 'cacheable_600s',
    supportsPreview: true,
    supportsUndo: false,
    timeoutMs: 3000,
    auditEventType: 'TOOL_MUSICSCALE_SEARCH_LIVING_LIBRARY',
  },
  {
    id: 'tool_musicscale_add_song_to_living_library',
    appId: 'musicscale',
    name: 'addSongToLivingLibrary',
    version: '2.0.0',
    title: 'Adicionar à Biblioteca Viva (Global)',
    description: 'Homologa uma nova música ou arranjo no acervo global do ecossistema MillionsNest.',
    inputSchema: JSON.stringify({ title: 'string', artist: 'string', isrc: 'string', bpm: 'number', defaultKey: 'string' }),
    outputSchema: JSON.stringify({ globalSongId: 'string', status: 'string' }),
    requiredPermissions: ['livingLibrary.manage'],
    organizationScoped: false,
    riskLevel: 'R3_PRIVILEGED',
    confirmationPolicy: 'admin_approval',
    readOnly: false,
    idempotencyPolicy: 'unique_request_id',
    supportsPreview: true,
    supportsUndo: false,
    timeoutMs: 6000,
    auditEventType: 'TOOL_MUSICSCALE_ADD_LIVING_LIBRARY',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'cnv_01',
    contactId: 'cnt_01',
    contactName: 'Gabriel Santos',
    contactAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    channel: 'whatsapp',
    channelIdentifier: '+55 43 99990-7071',
    mode: 'automatico',
    status: 'aberto',
    priority: 'media',
    organizationId: 'org_londrina_01',
    tags: ['MusicScale', 'Teclado', 'Escala'],
    lastMessageSnippet: 'Qual é a minha próxima escala no culto de domingo?',
    lastMessageAt: '2026-07-26T13:45:00Z',
    unreadCount: 1,
    aiSummary: 'O músico Gabriel perguntou sobre sua próxima escala no MusicScale. A IA identificou vínculo e recuperou a escala de 28/07.',
    aiIntent: 'consultar_escala',
    aiSentiment: 'positivo',
  },
  {
    id: 'cnv_02',
    contactId: 'cnt_02',
    contactName: 'Mariana Costa',
    contactAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    channel: 'whatsapp',
    channelIdentifier: '+55 43 99990-7071',
    mode: 'com_aprovacao',
    status: 'aguardando_humano',
    priority: 'alta',
    organizationId: 'org_londrina_01',
    tags: ['Aguardando Humano', 'Vocal'],
    lastMessageSnippet: 'Preciso trocar meu dia de escala de domingo para sábado por motivo de viagem.',
    lastMessageAt: '2026-07-26T12:10:00Z',
    unreadCount: 2,
    aiSummary: 'A cantora solicita alteração de data na escala. Requisição exige aprovação de ferramenta de troca de integrante.',
    aiIntent: 'solicitar_troca_escala',
    aiSentiment: 'urgente',
  },
  {
    id: 'cnv_03',
    contactId: 'cnt_03',
    contactName: 'Carlos Eduardo',
    contactAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    channel: 'instagram',
    channelIdentifier: '@millionsnest_official',
    mode: 'automatico',
    status: 'aberto',
    priority: 'baixa',
    organizationId: 'org_londrina_01',
    tags: ['Lead Instagram', 'Dúvida'],
    lastMessageSnippet: 'Como funciona o aplicativo MusicScale para nossa equipe de música?',
    lastMessageAt: '2026-07-26T10:00:00Z',
    unreadCount: 0,
    aiSummary: 'Lead perguntando como contratar e usar o MusicScale na igreja dele. Agente de recepção respondeu com o menu do ecossistema.',
    aiIntent: 'informacao_produto',
    aiSentiment: 'neutro',
  },
];

export const mockMessages: Record<string, UnifiedMessage[]> = {
  cnv_01: [
    {
      id: 'msg_101',
      conversationId: 'cnv_01',
      senderType: 'contact',
      senderName: 'Gabriel Santos',
      content: 'Paz do Senhor! Qual é a minha próxima escala no culto de domingo no MusicScale?',
      createdAt: '2026-07-26T13:42:00Z',
    },
    {
      id: 'msg_102',
      conversationId: 'cnv_01',
      senderType: 'agent',
      senderName: 'Suporte MusicScale (Agente IA)',
      content: 'A paz, Gabriel! Vou consultar o MusicScale para você agora mesmo.',
      createdAt: '2026-07-26T13:42:30Z',
      toolInvocation: {
        toolId: 'tool_musicscale_list_schedules',
        toolName: 'listSchedules',
        appId: 'musicscale',
        args: { organizationId: 'org_londrina_01', memberId: 'usr_mn_8812' },
        status: 'executed',
        riskLevel: 'R1_AUTH_READ',
        requiresApproval: false,
        executedAt: '2026-07-26T13:42:32Z',
        result: {
          scheduleDate: '2026-07-28',
          serviceName: 'Culto de Celebração - 19h',
          instrument: 'Teclado Principal',
          repertoire: ['Porque Ele Vive', 'Vim Para Adorar-te', 'Graça Imensurável'],
          confirmationStatus: 'Confirmado',
        },
      },
    },
    {
      id: 'msg_103',
      conversationId: 'cnv_01',
      senderType: 'agent',
      senderName: 'Suporte MusicScale (Agente IA)',
      content: 'Sua próxima escala é no **Domingo (28/07) às 19h00** no *Culto de Celebração*.\n\n🎸 **Instrumento:** Teclado Principal\n🎵 **Repertório:**\n1. Porque Ele Vive (Tom: G)\n2. Vim Para Adorar-te (Tom: E)\n3. Graça Imensurável (Tom: A)\n\nSua presença já constava como **Confirmada**. Precisa do link da cifra ou do arranjo da Biblioteca Viva?',
      createdAt: '2026-07-26T13:43:00Z',
    },
    {
      id: 'msg_104',
      conversationId: 'cnv_01',
      senderType: 'human_agent',
      senderName: 'Pr. Daniel Cunha',
      content: 'Deixei a gravação do ensaio no grupo do louvor, Gabriel!',
      createdAt: '2026-07-26T13:44:00Z',
      isInternalNote: true,
    },
    {
      id: 'msg_105',
      conversationId: 'cnv_01',
      senderType: 'contact',
      senderName: 'Gabriel Santos',
      content: 'Maravilha! Obrigado. Posso adicionar a música "Bondade de Deus" na Biblioteca Viva global?',
      createdAt: '2026-07-26T13:45:00Z',
    },
  ],
  cnv_02: [
    {
      id: 'msg_201',
      conversationId: 'cnv_02',
      senderType: 'contact',
      senderName: 'Mariana Costa',
      content: 'Olá! Preciso trocar meu dia de escala de domingo para sábado por motivo de viagem.',
      createdAt: '2026-07-26T12:08:00Z',
    },
    {
      id: 'msg_202',
      conversationId: 'cnv_02',
      senderType: 'agent',
      senderName: 'Suporte MusicScale (Agente IA)',
      content: 'Entendido, Mariana. A troca de voluntários em escalas ativas requer confirmação do responsável de louvor. Vou transferir este atendimento para a fila humana com aprovação.',
      createdAt: '2026-07-26T12:10:00Z',
    },
  ],
  cnv_03: [
    {
      id: 'msg_301',
      conversationId: 'cnv_03',
      senderType: 'contact',
      senderName: 'Carlos Eduardo',
      content: 'Como funciona o aplicativo MusicScale para nossa equipe de música?',
      createdAt: '2026-07-26T10:00:00Z',
    },
    {
      id: 'msg_302',
      conversationId: 'cnv_03',
      senderType: 'agent',
      senderName: 'Recepção MillionsNest (Agente IA)',
      content: 'Olá Carlos! O **MusicScale** é o aplicativo de gestão de louvor do ecossistema MillionsNest. Ele oferece:\n\n1. Gestão automática de escalas e confirmações via WhatsApp\n2. Cifras e arranjos sincronizados no celular dos músicos\n3. Acesso à Biblioteca Viva compartilhada\n\nDeseja ver uma demonstração das opções do menu?',
      createdAt: '2026-07-26T10:01:00Z',
    },
  ],
};

export const mockAgents: AgentDefinition[] = [
  {
    id: 'ag_recapcao',
    name: 'Recepção MillionsNest',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    channelScope: ['whatsapp', 'instagram', 'inapp'],
    version: '2.4.1',
    autonomyMode: 'responder_automaticamente',
    status: 'ativo',
    resolutionRate: 88.4,
    goals: ['Boas-vindas', 'Apresentação de apps', 'Qualificação inicial de contato'],
    knowledgeSourceIds: ['kn_01', 'kn_02'],
    allowedToolIds: ['tool_musicscale_search_living_library'],
    blockedThemes: ['Aconselhamento pastoral profundo', 'Assuntos financeiros privados', 'Acesso direto a banco'],
    transferPolicy: 'Transferir imediatamente ao solicitar atendente ou falar de assunto sensível.',
    costLimitMonthly: 150.0,
    currentCostMonthly: 34.2,
    language: 'pt-BR',
    promptStructure: {
      role: 'Assistente amigável de recepção do ecossistema MillionsNest',
      systemDirective: 'Responda com cordialidade, apresente o ecossistema MillionsNest e encaminhe dúvidas técnicas para ferramentas autorizadas.',
      guardrails: ['Nunca simular dados financeiros', 'Respeitar a autoridade dos apps do ecossistema'],
    },
    versions: [
      { version: '2.4.1', updatedAt: '2026-07-15T00:00:00Z', updatedBy: 'Pr. Daniel Cunha', changelog: 'Ajuste no tom de voz para acolhimento' },
      { version: '2.4.0', updatedAt: '2026-06-01T00:00:00Z', updatedBy: 'Pr. Daniel Cunha', changelog: 'Inclusão do menu dinâmico do WhatsApp' },
    ],
  },
  {
    id: 'ag_musicscale',
    name: 'Suporte MusicScale',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    channelScope: ['whatsapp', 'inapp'],
    version: '3.1.0',
    autonomyMode: 'executar_ferramentas_com_confirmacao',
    status: 'ativo',
    resolutionRate: 92.1,
    goals: ['Consultar escalas', 'Confirmar voluntários', 'Buscar cifras', 'Adicionar sugestões'],
    knowledgeSourceIds: ['kn_02', 'kn_03'],
    allowedToolIds: [
      'tool_musicscale_list_schedules',
      'tool_musicscale_get_schedule',
      'tool_musicscale_create_schedule_draft',
      'tool_musicscale_list_repertoire',
      'tool_musicscale_search_living_library',
    ],
    blockedThemes: ['Alteração de billing da igreja', 'Exclusão imotiva de integrantes'],
    transferPolicy: 'Se o voluntário solicitar troca de data ou reportar indisponibilidade de última hora, acione modo humano.',
    costLimitMonthly: 300.0,
    currentCostMonthly: 98.5,
    language: 'pt-BR',
    promptStructure: {
      role: 'Agente especialista do MusicScale',
      systemDirective: 'Auxilie líderes de louvor e músicos a consultarem escalas e cifras mantendo o rigor das permissões.',
      guardrails: ['Não permitir alteração sem confirmação', 'Validar vinculação de conta antes de exibir dados privados'],
    },
    versions: [
      { version: '3.1.0', updatedAt: '2026-07-20T00:00:00Z', updatedBy: 'Pr. Daniel Cunha', changelog: 'Suporte a rascunhos de escala' },
    ],
  },
  {
    id: 'ag_leads',
    name: 'Qualificação de Leads',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    channelScope: ['instagram'],
    version: '1.0.5',
    autonomyMode: 'so_sugerir',
    status: 'ativo',
    resolutionRate: 76.0,
    goals: ['Responder Directs do Instagram', 'Apresentar planos da plataforma', 'Agendar demonstração com equipe'],
    knowledgeSourceIds: ['kn_01'],
    allowedToolIds: [],
    blockedThemes: ['Negociação de desconto sem autorização'],
    transferPolicy: 'Sugerir agendamento e passar para equipe comercial.',
    costLimitMonthly: 100.0,
    currentCostMonthly: 12.8,
    language: 'pt-BR',
    promptStructure: {
      role: 'Qualificador de oportunidades de relacionamento',
      systemDirective: 'Atenda visitantes no Instagram com respostas ágeis e convide para o teste do MusicScale.',
      guardrails: ['Não oferecer garantias não homologadas'],
    },
    versions: [{ version: '1.0.5', updatedAt: '2026-05-10T00:00:00Z', updatedBy: 'Pr. Daniel Cunha', changelog: 'Ajuste de copy para Instagram Direct' }],
  },
];

export const mockKnowledgeSources: KnowledgeSource[] = [
  {
    id: 'kn_01',
    title: 'Visão Geral e Manifesto MillionsNest',
    type: 'pagina',
    owner: 'Pr. Daniel Cunha',
    scope: 'global',
    language: 'pt-BR',
    version: '1.0',
    status: 'revisado',
    lastUpdatedAt: '2026-01-10T00:00:00Z',
    contentSnippet: 'O ecossistema MillionsNest conecta ferramentas de ministério, gestão de louvor e saúde financeira das igrejas com autoridade descentralizada e governança rigorosa.',
  },
  {
    id: 'kn_02',
    title: 'Política de Escalas e Prazos do MusicScale',
    type: 'politica',
    owner: 'Equipe de Louvor Central',
    scope: 'organizacao',
    organizationId: 'org_londrina_01',
    language: 'pt-BR',
    version: '2.1',
    status: 'revisado',
    lastUpdatedAt: '2026-06-15T00:00:00Z',
    contentSnippet: 'Confirmações de escala devem ocorrer até 48 horas antes do culto. Trocas de última hora exigem aviso imediato e validação do líder de naipe.',
  },
  {
    id: 'kn_03',
    title: 'Diretrizes de Curadoria da Biblioteca Viva',
    type: 'documento',
    owner: 'Conselho de Louvor Global',
    scope: 'global',
    language: 'pt-BR',
    version: '1.5',
    status: 'revisado',
    validUntil: '2027-12-31T23:59:59Z',
    lastUpdatedAt: '2026-04-01T00:00:00Z',
    contentSnippet: 'Para homologar uma cifra na Biblioteca Viva é necessário código ISRC válido ou identificação do autor, tom padrão e notação cifrada simplificada.',
  },
];

export const mockAutomations: AutomationDefinition[] = [
  {
    id: 'aut_01',
    name: 'Boas-Vindas a Leads do Instagram',
    trigger: 'Mensagem recebida via Instagram Direct sem cadastro',
    condition: 'Horário comercial ou fim de semana',
    action: 'Enviar menu conversacional público e notificar atendente de plantão',
    status: 'ativo',
    executionsCount: 142,
    blocks: [
      { id: 'b1', type: 'trigger', label: 'Instagram Direct Recebido', config: 'Canal: Instagram Direct' },
      { id: 'b2', type: 'condition', label: 'Contato sem vínculo MillionsNest?', config: 'Status: nao_vinculado' },
      { id: 'b3', type: 'action', label: 'Enviar Menu de Boas-Vindas', config: 'Menu: Conhecer os Aplicativos' },
      { id: 'b4', type: 'wait', label: 'Aguardar 10 minutos por resposta', config: 'Timeout: 600s' },
    ],
  },
  {
    id: 'aut_02',
    name: 'Lembrete de Escala Sem Confirmação',
    trigger: 'Escala do MusicScale com voluntários pendentes há 24h',
    condition: 'Faltam 3 dias para o culto',
    action: 'Enviar mensagem WhatsApp personalizada com botão de confirmação rápida',
    status: 'ativo',
    executionsCount: 389,
    blocks: [
      { id: 'b10', type: 'trigger', label: 'Cron: Verificação de Escala', config: 'A cada 6 horas' },
      { id: 'b11', type: 'condition', label: 'Voluntário não confirmou?', config: 'Status: pendente' },
      { id: 'b12', type: 'action', label: 'Disparar Notificação WhatsApp', config: 'Template: Lembrete de Escala' },
    ],
  },
];

export const mockChannels: ChannelConnection[] = [
  {
    id: 'chn_wa',
    type: 'whatsapp',
    name: 'WhatsApp Oficial - MillionsNest',
    identifier: '+55 43 99990-7071',
    status: 'saudavel',
    lastSync: '2026-07-26T14:00:00Z',
    webhookUrl: 'https://connect.millionsnest.com/api/webhooks/whatsapp',
    errorCount: 0,
    coexistenceStatus: 'Planejado para coexistência oficial com Meta Cloud API / BSP',
    details: {
      provider: 'Meta Business Cloud API (Planejado)',
      phoneNumber: '+55 43 99990-7071',
      qualityRating: 'ALTA (GREEN)',
      messagesToday: '1,248',
    },
  },
  {
    id: 'chn_ig',
    type: 'instagram',
    name: 'Instagram @millionsnest_official',
    identifier: '@millionsnest_official',
    status: 'saudavel',
    lastSync: '2026-07-26T13:58:00Z',
    webhookUrl: 'https://connect.millionsnest.com/api/webhooks/instagram',
    errorCount: 1,
    coexistenceStatus: 'Ativo para respostas privadas de Direct e comentários',
    details: {
      accountType: 'Conta Profissional Conectada',
      pageConnected: 'MillionsNest Official',
      directMessages: 'Ativado',
      commentReplies: 'Ativado (Planejado)',
    },
  },
  {
    id: 'chn_inapp',
    type: 'inapp',
    name: 'In-app Connect Widget',
    identifier: 'widget.connect.millionsnest.com',
    status: 'saudavel',
    lastSync: '2026-07-26T14:05:00Z',
    webhookUrl: 'https://connect.millionsnest.com/api/webhooks/inapp',
    errorCount: 0,
    coexistenceStatus: 'Widget nativo integrado aos apps MusicScale e NestFinance',
    details: {
      activeSessions: '42',
      sdkVersion: '1.4.0',
    },
  },
];

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'aud_1001',
    requestId: 'req_a9821f00',
    correlationId: 'corr_88123912',
    actor: 'Agente IA (Suporte MusicScale)',
    organizationId: 'org_londrina_01',
    channel: 'whatsapp',
    conversationId: 'cnv_01',
    toolId: 'tool_musicscale_list_schedules',
    toolName: 'listSchedules',
    riskLevel: 'R1_AUTH_READ',
    requiredPermission: 'musicscale.schedules.view',
    confirmationState: 'auto',
    result: 'sucesso',
    details: 'Consulta de escala para Gabriel Santos (+5543998124455). Tenant validado no servidor.',
    timestamp: '2026-07-26T13:42:32Z',
  },
  {
    id: 'aud_1002',
    requestId: 'req_b11299cc',
    correlationId: 'corr_99812311',
    actor: 'Agente IA (Recepção MillionsNest)',
    organizationId: 'org_londrina_01',
    channel: 'whatsapp',
    conversationId: 'cnv_01',
    toolId: 'tool_musicscale_add_song_to_living_library',
    toolName: 'addSongToLivingLibrary',
    riskLevel: 'R3_PRIVILEGED',
    requiredPermission: 'livingLibrary.manage',
    confirmationState: 'blocked',
    result: 'negado',
    details: 'Membro solicitou adicionar música à Biblioteca Viva global sem a capability global livingLibrary.manage. Execução bloqueada pelo Tool Gateway.',
    timestamp: '2026-07-26T13:46:00Z',
    isLivingLibraryBlocked: true,
  },
  {
    id: 'aud_1003',
    requestId: 'req_c4455123',
    correlationId: 'corr_77123910',
    actor: 'Membro Externo (Injetado via Frontend)',
    organizationId: 'org_curitiba_02',
    channel: 'inapp',
    toolId: 'tool_musicscale_get_schedule',
    toolName: 'getSchedule',
    riskLevel: 'R1_AUTH_READ',
    requiredPermission: 'musicscale.schedules.view',
    confirmationState: 'blocked',
    result: 'negado',
    details: 'Tentativa de acesso Cross-Tenant detectada: Token pertence à org_londrina_01 mas solicitou org_curitiba_02. Bloqueio automático.',
    timestamp: '2026-07-26T11:20:00Z',
    isCrossTenantBlocked: true,
  },
  {
    id: 'aud_1004',
    requestId: 'req_d5566778',
    correlationId: 'corr_11223344',
    actor: 'Pr. Daniel Cunha',
    organizationId: 'org_londrina_01',
    channel: 'inapp',
    toolId: 'tool_musicscale_create_schedule_draft',
    toolName: 'createScheduleDraft',
    riskLevel: 'R2_REVERSIBLE_WRITE',
    requiredPermission: 'musicscale.schedules.manage',
    confirmationState: 'user_confirmed',
    result: 'sucesso',
    details: 'Rascunho de escala do culto de domingo criado com sucesso por administrador validado.',
    timestamp: '2026-07-25T16:30:00Z',
  },
];

export const mockAppManifests: AppManifest[] = [
  {
    appId: 'musicscale',
    name: 'MusicScale',
    iconName: 'Music',
    description: 'Plataforma oficial de gestão de louvor, escalas de músicos, repertório e acervo de cifras.',
    status: 'ativo',
    registeredToolsCount: 10,
  },
  {
    appId: 'nestfinance',
    name: 'NestFinance',
    iconName: 'Landmark',
    description: 'Gestão financeira ministerial, orçamentos, ofertas e prestação de contas transparente.',
    status: 'planejado',
    registeredToolsCount: 0,
  },
  {
    appId: 'connect_core',
    name: 'Connect Core',
    iconName: 'Bot',
    description: 'Motor omnichannel, orquestração de agentes e barramento de ferramentas do MillionsNest.',
    status: 'ativo',
    registeredToolsCount: 4,
  },
];
